### ISSUE TITLE
Cert

### ISSUE THREAD

**Issue by thedavejay** [wsilveiranz/EventHubsKafkaSample#1]
Hi there,

Where did you get the PEM file from? 

Kind regards,
David

**Comment by mattias01** [comment]
I don't know where the author got it from, but you can get the Mozilla Ca cert as a pem file from here:
https://curl.haxx.se/docs/caextract.html

**Comment by wsilveiranz** [comment]
Thanks for stepping in Mattias! And you are correct. This is from where I got the PEM files [https://curl.haxx.se/docs/caextract.html](https://curl.haxx.se/docs/caextract.html)

Sorry for the delay on the answer. Couple of long days at work.

Cheers, Wagner.
